[project]
name = "budgeapp"
version = "0.1.0"
description = "Backend API for Budge, a personal finance budgeting and forecasting app."
readme = "README.md"
authors = [{ name = "Jesse Brooklyn Hannah", email = "jesse@jbhannah.net" }]
requires-python = "==3.13.1"
dependencies = [
    "alembic==1.14.1",
    "argon2-cffi==23.1.0",
    "email-validator==2.2.0",
    "fastapi[standard]==0.115.6",
    "pyjwt[crypto]==2.10.1",
    "sqlalchemy[postgresql-asyncpg]==2.0.40",
    "sqlmodel==0.0.22",
]

[project.scripts]
budgeapp = "budgeapp:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["python-dotenv==1.0.1"]
test = [
    "faker==33.3.1",
    "gevent==24.11.1",
    "pytest==8.3.4",
    "pytest-asyncio==0.25.2",
    "pytest-cov==6.0.0",
    "pytest-xdist==3.6.1",
]

[tool.coverage.run]
concurrency = ["thread", "gevent"]

[tool.pytest.ini_options]
addopts = "-n 4"
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"
