"""
Add password hash to user table

Revision ID: abce8736d1a3
Revises: e11a405920b3
Create Date: 2025-01-02 21:14:48.037380

"""

from typing import Sequence, Union

import sqlalchemy as sa

import budgeapp.models.password
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abce8736d1a3"
down_revision: Union[str, None] = "e11a405920b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("password_hash", budgeapp.models.password.Password(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password_hash")
    # ### end Alembic commands ###
