name: Python

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install poetry
      - uses: actions/setup-python@v5.1.1
        with:
          cache: poetry
      - run: poetry install
  lint:
    runs-on: ubuntu-latest
    needs:
      - poetry
    steps:
      - uses: actions/checkout@v4
      - run: pip install poetry
      - uses: actions/setup-python@v5.1.1
        with:
          cache: poetry
      - run: poetry install
      - run: make lint
  test:
    runs-on: ubuntu-latest
    needs:
      - poetry
    steps:
      - uses: actions/checkout@v4
      - run: pip install poetry
      - uses: actions/setup-python@v5.1.1
        with:
          cache: poetry
      - run: poetry install
      - run: make test
